### ISSUE TITLE
Pcap_DNSProxy 无法启动

### ISSUE THREAD

**Issue by gaoyan1234** [wongsyrone/openwrt-Pcap_DNSProxy#10]
一启动就报错 
root@Jingtian-router:~# /etc/init.d/pcap-dnsproxy start
Hooray! Error.log not found
Pcap_DNSProxy failed to start
root@Jingtian-router:~#
ps：没有动配置文件

**Comment by wongsyrone** [comment]
`/etc/init.d/pcap-dnsproxy libver`结果是什么，检验自己安装的对应依赖是不是对应的版本，如果不是，预编译包里面有

**Comment by wongsyrone** [comment]
另外从你上一个issue中opkg的安装信息来看，libsodium是1.0.2，libpcap 是1.5.3；但是提供的预编译包分别是1.0.9和1.7.4

**Comment by xayane** [comment]
我遇到了同样的问题：
root@ironman:/etc/dnsmasq.d# /etc/init.d/pcap-dnsproxy start
Hooray! Error.log not found
root@ironman:/etc/dnsmasq.d# /etc/init.d/pcap-dnsproxy libver
Bus error

Bus error是个什么鬼。。。

**Comment by wongsyrone** [comment]
Make sure you have installed correct dependencies.

**Comment by xayane** [comment]
@wongsyrone 我重新下载了SDK
编译后生成的libpcap libsodium libstdcpp和lede官网上的packages的版本号的都一致。
安装pcap_dnsproxy之后仍然是显示“Hooray! Error.log not found”和“Bus error”
这几天重复试了好几次了。还有哪里弄错了啊？

**Comment by wongsyrone** [comment]
Check arch and endianness.

**Comment by xayane** [comment]
arch and endianness是指sha256校验值吗？
我看了一下，两个有问题，sha256值不一样。那是我SDK的问题还是？

**Comment by xayane** [comment]
可是SDK是在lede官网下载的，我发现他每天都会更新，和这个有关系吗？

**Comment by wongsyrone** [comment]
应该没关系，我很少用SDK，还是建议直接用代码树，可能你SDK不完整或者SDK本身有bug没修

**Comment by xayane** [comment]
thank you!
And i git clone the lede source.git as your suggestion and then compile follow your documents.
and there is another error "cp: cannot stat '/home/uk/source/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-5.4.0_musl-1.1.15_eabi/lib/libgcc_s.so.*': No such file or directory"

i googled and there was a solution:
copy "/usr/lib/gcc/x86_64-linux-gnu/4.9.2/libgcc_s.so.*" to your "./lib"
but i check my "/usr/lib/gcc/x86_64-linux-gnu/4.9.2/", there is only "libgcc_s.so"
so i still got the compile error....
sorry to ask for help again...
