### ISSUE TITLE
只要使用 Local Hosts ，就出现错误 Regular expression pattern error

### ISSUE THREAD

**Issue by matthew728960** [wongsyrone/openwrt-Pcap_DNSProxy#12]
每一行都出错，为了简洁之列出几句。都是相同的错误（从 WhiteList.txt 的第一行到最后一行）

    Hosts Error: Regular expression pattern error in line 767 of /etc/pcap_dnsproxy/WhiteList.txt, error code is 2.
    Hosts Error: Regular expression pattern error in line 768 of /etc/pcap_dnsproxy/WhiteList.txt, error code is 2.
    Hosts Error: Regular expression pattern error in line 769 of /etc/pcap_dnsproxy/WhiteList.txt, error code is 2.

**Comment by wongsyrone** [comment]
预编译包不支持正则，因为GCC 4.8对C++11的STL支持有问题，请自行编译针对trunk的版本

**Comment by matthew728960** [comment]
哦，看到注意那里了。谢谢！
