### ISSUE TITLE
编译出错，求指导

### ISSUE THREAD

**Issue by xJetRy** [wongsyrone/openwrt-Pcap_DNSProxy#16]
第一次编译，自己实在搞不定了求帮忙分析下哪里出错了
系统Ubuntu 14.04.1_64bit
装了基础环境：
sudo apt-get install build-essential asciidoc binutils bzip2 gawk gettext git subversion libssl-dev libncurses5-dev  patch unzip zlib1g-dev ccache mercurial libc6:i386 libgcc1:i386 libstdc++5:i386 libstdc++6:i386
然后依次执行：
git clone git://git.openwrt.org/15.05/openwrt.git
cd openwrt
git clone --depth 1 --branch master --single-branch https://github.com/wongsyrone/openwrt-Pcap_DNSProxy.git package/pcap-dnsproxy
make menuconfig   在Network里选中pcap-dnsproxy后保存.config然后退出
make package/pcap-dnsproxy/{prepare,compile} V=99

编译报错，报错部分如下：
cp -fpR /home/xjetry/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libuClibc-*.so /home/xjetry/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libcrypt-*.so /home/xjetry/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libm-*.so /home/xjetry/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libpthread-*.so /home/xjetry/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/toolchain/
cp: cannot stat '/home/xjetry/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libuClibc-*.so': No such file or directory
cp: cannot stat '/home/xjetry/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libcrypt-*.so': No such file or directory
cp: cannot stat '/home/xjetry/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libm-*.so': No such file or directory
cp: cannot stat '/home/xjetry/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libpthread-*.so': No such file or directory
Makefile:636: recipe for target '/home/xjetry/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/toolchain/.built' failed
make[2]: *** [/home/xjetry/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/toolchain/.built] Error 1
make[2]: Leaving directory '/home/xjetry/openwrt/package/libs/toolchain'
package/Makefile:191: recipe for target 'package/libs/toolchain/compile' failed
make[1]: *** [package/libs/toolchain/compile] Error 2
make[1]: Leaving directory '/home/xjetry/openwrt'
/home/xjetry/openwrt/include/toplevel.mk:181: recipe for target 'package/pcap-dnsproxy/compile' failed
make: *** [package/pcap-dnsproxy/compile] Error 2

用SDK编译，报错如下：
Scanning dependencies of target Pcap_DNSProxy
make[5]: Leaving directory '/home/xjetry/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.6.5'
make[5]: Entering directory '/home/xjetry/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.6.5'
[  5%] Building CXX object Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
In file included from /home/xjetry/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.6.5/Source/Pcap_DNSProxy/Structures.h:20:0,
                 from /home/xjetry/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.6.5/Source/Pcap_DNSProxy/Base.h:20,
                 from /home/xjetry/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.6.5/Source/Pcap_DNSProxy/Base.cpp:20:
/home/xjetry/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mips_34kc_uClibc-0.9.33.2/pcap-dnsproxy-0.4.6.5/Source/Pcap_DNSProxy/Platform.h:296:23: fatal error: sodium.h: No such file or directory
    #include <sodium.h>
                       ^
compilation terminated.
Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/build.make:57: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o' failed
make[5]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o] Error 1

**Comment by wongsyrone** [comment]
第一个貌似是编译环境不完整，检查你下载的SDK或者代码树完整性。
第二个是缺少编译依赖libsodium，仔细看编译教程。

**Comment by zasl** [comment]
我在聊天室发了，麻烦看看啊，也是2个方法都无法编译

**Comment by wongsyrone** [comment]
@zasl 
你的信息太简略了，看不出来是哪里的问题。建议整理发个issue，从头到尾说的详细一点。

**Comment by zasl** [comment]
@wongsyrone 你好，是否能提供一个更加好一些的联系方式？因为我是新手，不知道如何提供更加完整的信息。

**Comment by zasl** [comment]
你好，能否通过一些其他交流工具来提供帮助，因为我是纯新手，所以提供的东西无法特别符合你的要求。而网站联系时限又比较长。

2016-08-16 7:54 GMT+08:00 Syrone Wong <notifications@github.com>:

**Comment by wongsyrone** [comment]
邮箱或者github issue，地址在profile页面有。
