### ISSUE TITLE
编译出4663，但是无法启动

### ISSUE THREAD

**Issue by zasl** [wongsyrone/openwrt-Pcap_DNSProxy#17]
/etc/pcap-dnsproxy$ /etc/init.d/pcap-dnsproxy start
Hooray! Error.log not found
Pcap_DNSProxy failed to start

在目录下增加error.log文件，命令启动会删除继续提示

**Comment by zasl** [comment]
/etc/pcap-dnsproxy$ /etc/init.d/pcap-dnsproxy start
Hooray! Error.log not found
Pcap_DNSProxy failed to start

在目录下增加error.log文件，命令启动会删除继续提示

**Comment by wongsyrone** [comment]
那个提示是没有错误日志欢呼 ，如果提示你存在错误日志，自己看一下。如果程序闪退 ，目前来说，没有什么好办法，手动重启多次，这个问题还没找到根源。

**Comment by wongsyrone** [comment]
另外参见https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/issues/18#issuecomment-241709817
