### ISSUE TITLE
程序无法启动

### ISSUE THREAD

**Issue by shuangzhijinghua** [wongsyrone/openwrt-Pcap_DNSProxy#18]
![image](https://cloud.githubusercontent.com/assets/7972337/17887292/60c251f0-6958-11e6-8084-2774572e52b0.png)

这就很神奇了...也是遇到和上一个issue里面一样的问题，安装的同时我也安装了最新的libpcap和libsodium。尝试chmod 777 Pcap_DNSProxy也无效，都是无法找到。尝试更改日志文件输出路径无效。

**Comment by shuangzhijinghua** [comment]
顺带说一下代码是git clone git://git.openwrt.org/openwrt拉下来的，然后看了一下libc并不一样。知道问题所在了，openwrt 15.05.1的libc是用gcc4.8编译的，但是最新版 代码的GCC是5.3，导致了不兼容的问题。

**Comment by wongsyrone** [comment]
如果使用trunk，就自己编译到固件里，如果坚持使用所谓的稳定版BB，CC，就用SDK，两个不能混。
