### ISSUE TITLE
dns转发问题

### ISSUE THREAD

**Issue by zasl** [wongsyrone/openwrt-Pcap_DNSProxy#19]
请问在dnsmasq.conf添加了server=192.168.1.1#1053还是否需要在openwrt的DHCP/DNS添加转发地址127.0.0.1#1053？

**Comment by wongsyrone** [comment]
不用。流程是：客户端-》dnsmasq-》pcap-dnsproxy-》DNS服务器

**Comment by zasl** [comment]
好的，非常感谢。
