### ISSUE TITLE
CONFIG_CCACHE is not set

### ISSUE THREAD

**Issue by xayane** [wongsyrone/openwrt-Pcap_DNSProxy#20]
根据documents的说明：
“# 进入 SDK 根目录
cd OpenWrt-SDK-*
# 首先验证 SDK 是否需要 ccache
cat .config | grep CONFIG_CCACHE”

我在输入“cat .config | grep CONFIG_CCACHE”之后，显示的是：
-bash CONFIG_CCACHE is not set

小白求问，这个是什么问题，需要怎么做？google了一下，也没有看到答案。。谢谢
我实在搬瓦工上操作的，Operating system:	Debian 8.0 x86_64

**Comment by wongsyrone** [comment]
如果返回的不是“y”可以不用管它，或者没遇到https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/issues/1#issuecomment-150821950 这个也可以不用管

**Comment by xayane** [comment]
好滴，谢谢！
果然没管编译成功，bin下面有packages和targets两个文件夹，里面合起来有10来个ipk，弱问，这么多ipk都需要安装吗？

**Comment by wongsyrone** [comment]
安装依赖库libsodium和libpcap以及主程序

**Comment by xayane** [comment]
OK，3Q！我试试，感谢！
也感谢作者 @chengr28 ，win下就非常好用。
