### ISSUE TITLE
请问这样的日志是否正常

### ISSUE THREAD

**Issue by zasl** [wongsyrone/openwrt-Pcap_DNSProxy#22]
看起来的error很多。不知道是否正常？
Fri Sep 23 20:33:55 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:33:55 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:33:55 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:33:55 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:33:55 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:33:55 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:33:55 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:33:55 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:33:57 2016 daemon.err uhttpd[3424]: uci: Entry not found
Fri Sep 23 20:33:58 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:33:58 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:33:58 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:33:58 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Fri Sep 23 20:33:59 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:33:59 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:00 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:00 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:00 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:00 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:34:00 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:00 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:00 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:00 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:00 2016 cron.info crond[2058]: USER root pid 29544 cmd pcap.sh
Fri Sep 23 20:34:00 2016 cron.info crond[2058]: USER root pid 29545 cmd ssr.sh
Fri Sep 23 20:34:01 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:01 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:03 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:03 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:03 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:03 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Fri Sep 23 20:34:04 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:04 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:05 2016 daemon.err uhttpd[3424]: error connecting to ocserv socket '/var/run/occtl.socket': No such file or directory
Fri Sep 23 20:34:05 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:05 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:05 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:05 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:34:05 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:05 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:05 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:05 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:06 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:06 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:07 2016 daemon.err uhttpd[3424]: uci: Entry not found
Fri Sep 23 20:34:08 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:08 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:08 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:08 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Fri Sep 23 20:34:08 2016 daemon.err uhttpd[3424]: error connecting to ocserv socket '/var/run/occtl.socket': No such file or directory
Fri Sep 23 20:34:10 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:10 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:10 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:10 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:10 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:10 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:34:10 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:10 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:12 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:12 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:12 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:12 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:13 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:13 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:13 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:13 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Fri Sep 23 20:34:15 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:15 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:15 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:15 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:34:15 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:15 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:15 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:15 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:16 2016 daemon.err uhttpd[3424]: uci: Entry not found
Fri Sep 23 20:34:17 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:17 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:18 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:18 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:18 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:18 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Fri Sep 23 20:34:18 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:18 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:20 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:20 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:20 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:20 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:20 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:20 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:20 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:20 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:34:23 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:23 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:23 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:23 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Fri Sep 23 20:34:23 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:23 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:24 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:24 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:25 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:25 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:25 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:25 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:25 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:25 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:34:25 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:25 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:25 2016 daemon.err uhttpd[3424]: uci: Entry not found
Fri Sep 23 20:34:26 2016 daemon.err uhttpd[3424]: error connecting to ocserv socket '/var/run/occtl.socket': No such file or directory
Fri Sep 23 20:34:27 2016 daemon.err uhttpd[3424]: error connecting to ocserv socket '/var/run/occtl.socket': No such file or directory
Fri Sep 23 20:34:28 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:28 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:28 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:28 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Fri Sep 23 20:34:28 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:28 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:29 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:29 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:30 2016 daemon.err uhttpd[3424]: uci: Entry not found
Fri Sep 23 20:34:30 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:30 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:30 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:30 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:34:30 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:30 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:30 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:30 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:33 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:33 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:33 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:33 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.
Fri Sep 23 20:34:35 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:35 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:35 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:35 -> DNSCurve Error: IPv6 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:35 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:35 -> Network Error: Socket connecting error, error code is 13.
Fri Sep 23 20:34:35 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:35 -> DNSCurve Error: IPv6 Main Server UDP get signature data error.
Fri Sep 23 20:34:35 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:35 -> DNSCurve Error: IPv4 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:36 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:36 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
Fri Sep 23 20:34:38 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:38 -> DNSCurve Error: IPv6 Alternate Server TCP get signature data error.
Fri Sep 23 20:34:38 2016 daemon.err Pcap_DNSProxy[7375]: 2016-09-23 20:34:38 -> DNSCurve Error: IPv6 Main Server TCP get signature data error.

**Comment by chengr28** [comment]
See https://github.com/chengr28/Pcap_DNSProxy/issues/193
