### ISSUE TITLE
SDK怎么升级使用gcc 4.9或者以上

### ISSUE THREAD

**Issue by cpexplorer** [wongsyrone/openwrt-Pcap_DNSProxy#24]
下载的sdk默认带的gcc都是4.8了，然后看到博主这一段话“如果 SDK 的文件名注明 GCC 版本为 4.8，由于该版本的 GCC 对 STL 的正则表达式支持不完整，会导致有些 Hosts 那边的正则表达式用不了，如果确实需要使用正则表达式，请使用 GCC 4.9 或以上版本编译。”，想问使用GCC4.9或者以上如何在SDK里实现

**Comment by wongsyrone** [comment]
用LEDE或者自己编译SDK
