### ISSUE TITLE
自动启动脚本有BUG？

### ISSUE THREAD

**Issue by wang20150419** [wongsyrone/openwrt-Pcap_DNSProxy#25]
openwrt cc, 可以手工启动，工作也正常。
但用自动运行脚本无法启动。

用命令行：
     Pcap_DNSProxy -c /etc/pcap-dnsproxy  
可以正常启动。
但：
     /etc/init.d/pcap-dnsproxy start 
无法启动。

**Comment by wongsyrone** [comment]
用LEDE，我这里稳定一周没问题。
