### ISSUE TITLE
pdnsd+pcap-dnsproxy以及pcap-dnsproxy+ss-local

### ISSUE THREAD

**Issue by cpexplorer** [wongsyrone/openwrt-Pcap_DNSProxy#28]
曾经在issue看博主说pdnsd+pcap不错，想问下这样组合的缘由，如果是看中pdnsd的缓存的话，pcap不也有么？还有如果用pcap+sslocal,会不会效果也不错？这俩方案会不会单比pcap有效果上的提升（不考虑资源占用）？

**Comment by wongsyrone** [comment]
pdnsd只是为了提供一个永久缓存，因为pcap自己的存储期有限制，不管是队列长度还是超时都比较短。而pdnsd的可定制性更高。另外pdnsd配置多种上游防污染查询的话，可以效率更高。

dnsmasq->pdnsd-> {upstream-servers}

**Comment by cpexplorer** [comment]
那pcap-dnsproxy+ss-local呢？会不会防污染上比单pcap-proxy更好？

**Comment by wongsyrone** [comment]
ss-local也不能查询dns啊，是ss-tunnel吧。这个要具体试过才知道，不同地区不同

**Comment by cpexplorer** [comment]
pcap的配置文件里是有socks相关的，那这个起到什么作用？
"* Proxy - 代理区域
  * SOCKS Proxy - SOCKS 协议总开关，控制所有和 SOCKS 协议有关的选项：开启为 1 /关闭为 0
  * SOCKS Version - SOCKS 协议所使用的版本：可填入 4 或 4A 或 5
    * SOCKS 版本 4 不支持 IPv6 地址以及域名的目标服务器，以及不支持 UDP 转发功能
    * SOCKS 版本 4a 不支持 IPv6 地址的目标服务器，以及不支持 UDP 转发功能
  * SOCKS Protocol - 发送 SOCKS 协议请求所使用的协议：可填入 IPv4 和 IPv6 和 TCP 和 UDP
    * 填入的协议可随意组合，只填 IPv4 或 IPv6 配合 UDP 或 TCP 时，只使用指定协议向 SOCKS 服务器发出请求
    * 同时填入 IPv4 和 IPv6 或直接不填任何网络层协议时，程序将根据网络环境自动选择所使用的协议
    * 同时填入 TCP 和 UDP 等于只填入 UDP 因为 TCP 为 SOCKS 最先支持以及最普遍支持的标准网络层协议，所以即使填入 UDP 请求失败时也会使用 TCP 请求
  * SOCKS UDP No Handshake - SOCKS UDP 不握手模式，开启后将不进行 TCP 握手直接发送 UDP 转发请求：开启为 1 /关闭为 0
    * SOCKS 协议的标准流程使用 UDP 转发功能前必须使用 TCP 连接交换握手信息，否则 SOCKS 服务器将直接丢弃转发请求
    * 部分 SOCKS 本地代理可以直接进行 UDP 转发而不需要使用 TCP 连接交换握手信息，启用前请务必确认 SOCKS 服务器的支持情况
  * SOCKS Proxy Only - 只使用 SOCKS 协议代理模式，所有请求将只通过 SOCKS 协议进行：开启为 1 /关闭为 0"

**Comment by cpexplorer** [comment]
另外，pcap更新到0.4.8了，博主有空更新下

**Comment by wongsyrone** [comment]
那个应该是前置代理。试过之前说的用旧办法重新编译吗，是否发现不能使用的问题？

**Comment by cpexplorer** [comment]
旧办法暂时还没有，改天再试试看

**Comment by wongsyrone** [comment]
嗯，等测试通过之后再考虑更新版，那个很简单的。
