### ISSUE TITLE
希望在wiki里说明如何设置为OpenWRT的上游DNS

### ISSUE THREAD

**Issue by matthew728960** [wongsyrone/openwrt-Pcap_DNSProxy#3]
如题，在Google上找不到相关的文章，又或者都没用。谢谢了！

**Comment by wongsyrone** [comment]
在dnsmasq的配置文件，比如/etc/dnsmasq.conf中添加`server=127.0.0.1#1053`如果修改了默认端口需要自行修改；同时建议添加`all-servers`参数并行请求上游DNS服务器。

**Comment by matthew728960** [comment]
谢谢！！

**Comment by wongsyrone** [comment]
信息于 1491aaa30dbc2643ea8c6113ccfc23ee2cbd2fbc 中添加
