### ISSUE TITLE
校园网，0.4.7.8-2能成功解析google等，升级到0.4.8.0无法解析

### ISSUE THREAD

**Issue by cpexplorer** [wongsyrone/openwrt-Pcap_DNSProxy#30]
0.4.7.8-2  dig @192.168.1.1 -p 1053 www.google.com能成功解析
升级到0.4.8.0则无法解析

**Comment by cpexplorer** [comment]
需要提供什么样的额外信息请明示；如果需要抓包的话可能得介绍下详细方法了，我对抓包不太了解

**Comment by wongsyrone** [comment]
先把模式改成Private

**Comment by wongsyrone** [comment]
和 https://github.com/chengr28/Pcap_DNSProxy/issues/210 应该差不多的问题

**Comment by cpexplorer** [comment]
测试了，确实是同样问题，改成Private就可以了。期待更新解决bug

**Comment by wongsyrone** [comment]
好，先关掉了
