### ISSUE TITLE
Entware-ng编译提示缺少头文件

### ISSUE THREAD

**Issue by ivyswen** [wongsyrone/openwrt-Pcap_DNSProxy#31]
`[  4%] Building CXX object Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
In file included from /bak/ivys/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/pcap-dnsproxy-0.4.8.1/Source/Pcap_DNSProxy/Structure.h:23:0,
                 from /bak/ivys/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/pcap-dnsproxy-0.4.8.1/Source/Pcap_DNSProxy/Definition.h:23,
                 from /bak/ivys/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/pcap-dnsproxy-0.4.8.1/Source/Pcap_DNSProxy/Template.h:2,
                 from /bak/ivys/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/pcap-dnsproxy-0.4.8.1/Source/Pcap_DNSProxy/Base.h:23,
                 from /bak/ivys/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/pcap-dnsproxy-0.4.8.1/Source/Pcap_DNSProxy/Base.cpp:20:
/bak/ivys/Entware-ng/build_dir/target-mipsel_mips32r2_uClibc-1.0.16/pcap-dnsproxy-0.4.8.1/Source/Pcap_DNSProxy/Platform.h:507:23: fatal error: sodium.h: No such file or directory
compilation terminated.`
pcap_dnsproxy-0.4.7.6版本是可以正常编译的，升级到0.4.8.1就不能正常编译了。

**Comment by wongsyrone** [comment]
> sodium.h: No such file

从错误上来说是缺少头文件

**Comment by wongsyrone** [comment]
可以尝试加两个定义PLATFORM_LINUX和PLATFORM_OPENWRT试一下能否过

**Comment by cpexplorer** [comment]
"sodium.h: No such file or directory compilation terminated."，应该是勾选了编译libsodium然后又找不到的缘故吧。把libsodium的makefile放在package下，编译时勾选进去应该就没问题了

**Comment by wongsyrone** [comment]
可能是libsodium的InstallDev定义的规则没有正确放入staging dir，或者是传入cmake的参数不全。因为没用过entware-ng，所以不太清楚。

**Comment by cpexplorer** [comment]
借用此楼跟你反馈个意见，因为pcap的配置项名称不时随着版本的更新在变，目前的ipk在卸载或者更新版本时是不会移除或者替换原来的配置文件的，是不是考虑在makefile中的preinst或者postinst中加个删除原来配置文件的语句？ @wongsyrone

**Comment by wongsyrone** [comment]
如果配置没有被修改是会被删除的，如果修改了就会自动保留，这是jffs2的特性，在overlayfs里面。如果需要手动调节一个rm -rf就好了啊，而且能够避免有人忘记备份修改的配置。所以不准备加
