### ISSUE TITLE
Hooray! Error.log not found

### ISSUE THREAD

**Issue by wang20150419** [wongsyrone/openwrt-Pcap_DNSProxy#33]
最新版本编译。
在 openwrt 的 ar71xx, mt7620 路由器上，以及最新的 lede ar71xx上，都是这个提示，运行不起来。

**Comment by mrw79** [comment]
用SSH工具连接路由，

输入命令：cat /etc/pcap-dnsproxy/Error.log，

就会显示错误在哪里。

修改/etc/pcap-dnsproxy/Config.conf，把上面显示的错误，修改。

**Comment by wongsyrone** [comment]
其实

```
Hooray! Error.log not found
```

这个提示是告诉你没有错误产生的，为了维持*nix的一致性，下个提交会去掉操作成功的提示。

**Comment by wang20150419** [comment]
原来是这么回事。害的我不敢用。

**Comment by wongsyrone** [comment]
Done.
