### ISSUE TITLE
lede下编译报错，请指教！

### ISSUE THREAD

**Issue by Sense1988** [wongsyrone/openwrt-Pcap_DNSProxy#36]
make[3]: Entering directory '/home/jungle/hdd/lede/package/lean/openwrt-Pcap_DNSProxy'touch /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.prepared_21469725a25aa88b56a56330c9eb22bf_6664517399ebbbc92a37c5bb081b5c53_check
. /home/jungle/hdd/lede/include/shell.sh; gzip -dc /home/jungle/hdd/lede/dl/pcap-dnsproxy-0.4.9.5-66c9f5b8315725ad369439fe688c6dbbc999b5e4.tar.gz | tar -C /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.. -xf - 
[ ! -d ./src/ ] || cp -fpR ./src/* /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5

Applying ./patches/002-cmake-dependency-scanner-workaround.patch using plaintext: 
patching file Source/Pcap_DNSProxy/Platform.h
rm -rf /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Dependency
touch /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.prepared_21469725a25aa88b56a56330c9eb22bf_6664517399ebbbc92a37c5bb081b5c53
rm -f /home/jungle/hdd/lede/staging_dir/target-x86_64_musl/stamp/.openwrt-Pcap_DNSProxy_installed
mkdir -p /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5
(cd /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5; CFLAGS="-pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5:pcap-dnsproxy-0.4.9.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -ansi -pedantic -Wall -Wextra -fpic -O3 " CXXFLAGS="-pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5:pcap-dnsproxy-0.4.9.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -ansi -pedantic -Wall -Wextra -fpic -O3 " LDFLAGS="-L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib -znow -zrelro " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_ASM_COMPILER="/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-gcc" -DCMAKE_ASM_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib -znow -zrelro" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_AR="/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-gcc-ar" -DCMAKE_NM="/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-gcc-nm" -DCMAKE_RANLIB="/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-gcc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr;/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/jungle/hdd/lede/staging_dir/target-x86_64_musl -DCMAKE_PREFIX_PATH=/home/jungle/hdd/lede/staging_dir/target-x86_64_musl -DCMAKE_SKIP_RPATH=TRUE -DPLATFORM_OPENWRT=ON -DENABLE_LIBSODIUM=ON -DENABLE_PCAP=ON -DENABLE_TLS=ON /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5 )
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-gcc
-- Check for working C compiler: /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-g++
-- Check for working CXX compiler: /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/bin/x86_64-openwrt-linux-musl-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found OpenSSL: /home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr/lib/libssl.so (found version "1.0.2l") 
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_ASM_COMPILER
    CMAKE_ASM_COMPILER_ARG1
    CMAKE_MODULE_LINKER_FLAGS
    CMAKE_SHARED_LINKER_FLAGS
    DL_LIBRARY

-- Build files have been written to: /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5
rm -f /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.configured_*
touch /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.built
touch /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.built_check
CFLAGS="-pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5:pcap-dnsproxy-0.4.9.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -ansi -pedantic -Wall -Wextra -fpic -O3  -I/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr/include -I/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/include -I/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/usr/include -I/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/include/fortify -I/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/include " CXXFLAGS="-pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5:pcap-dnsproxy-0.4.9.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -ansi -pedantic -Wall -Wextra -fpic -O3  -I/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr/include -I/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/include -I/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/usr/include -I/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/include/fortify -I/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/include " LDFLAGS="-L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/usr/lib -L/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib -znow -zrelro " make -j1 -C /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/. AR="x86_64-openwrt-linux-musl-gcc-ar" AS="x86_64-openwrt-linux-musl-gcc -c -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5:pcap-dnsproxy-0.4.9.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -ansi -pedantic -Wall -Wextra -fpic -O3" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-openwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-linux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-linux-musl-size CROSS="x86_64-openwrt-linux-musl-" ARCH="x86_64" CMAKE_COMMAND='/home/jungle/hdd/lede/staging_dir/host/bin/cmake' CMAKE_DISABLE_cmake_check_build_system=1 ;
make[4]: Entering directory '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5'
make[5]: Entering directory '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5'
make[6]: Entering directory '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5'
Scanning dependencies of target Pcap_DNSProxy
make[6]: Leaving directory '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5'
make[6]: Entering directory '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5'
[  4%] Building CXX object Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o
In file included from /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib/gcc/x86_64-openwrt-linux-musl/5.5.0/include/xmmintrin.h:34:0,
                 from /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib/gcc/x86_64-openwrt-linux-musl/5.5.0/include/x86intrin.h:31,
                 from /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/x86_64-openwrt-linux-musl/include/c++/5.5.0/x86_64-openwrt-linux-musl/bits/opt_random.h:33,
                 from /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/x86_64-openwrt-linux-musl/include/c++/5.5.0/random:50,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Platform.h:361,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Structure.h:23,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Definition.h:23,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Template.h:23,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Base.h:23,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Base.cpp:20:
/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib/gcc/x86_64-openwrt-linux-musl/5.5.0/include/mm_malloc.h:34:64: error: declaration of 'int posix_memalign(void**, size_t, size_t) throw ()' has a different exception specifier
 extern "C" int posix_memalign (void **, size_t, size_t) throw ();
                                                                ^
In file included from /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/x86_64-openwrt-linux-musl/include/c++/5.5.0/cstdlib:72:0,
                 from /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/x86_64-openwrt-linux-musl/include/c++/5.5.0/bits/stl_algo.h:59,
                 from /home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/x86_64-openwrt-linux-musl/include/c++/5.5.0/algorithm:62,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Platform.h:352,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Structure.h:23,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Definition.h:23,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Template.h:23,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Base.h:23,
                 from /home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/Source/Pcap_DNSProxy/Base.cpp:20:
/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/include/stdlib.h:99:5: error: from previous declaration 'int posix_memalign(void**, size_t, size_t)'
 int posix_memalign (void **, size_t, size_t);
     ^
Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/build.make:62: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o' failed
make[6]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/Base.cpp.o] Error 1
make[6]: Leaving directory '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5'
CMakeFiles/Makefile2:85: recipe for target 'Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/all' failed
make[5]: *** [Source/Pcap_DNSProxy/CMakeFiles/Pcap_DNSProxy.dir/all] Error 2
make[5]: Leaving directory '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5'
Makefile:129: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5'
Makefile:180: recipe for target '/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.built' failed
make[3]: *** [/home/jungle/hdd/lede/build_dir/target-x86_64_musl/pcap-dnsproxy-0.4.9.5/.built] Error 2
make[3]: Leaving directory '/home/jungle/hdd/lede/package/lean/openwrt-Pcap_DNSProxy'
package/Makefile:109: recipe for target 'package/lean/openwrt-Pcap_DNSProxy/compile' failed
make[2]: *** [package/lean/openwrt-Pcap_DNSProxy/compile] Error 2
make[2]: Leaving directory '/home/jungle/hdd/lede'
package/Makefile:105: recipe for target '/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/jungle/hdd/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/jungle/hdd/lede'
/home/jungle/hdd/lede/include/toplevel.mk:207: recipe for target 'world' failed
make: *** [world] Error 2
jungle@6700k:~/hdd/lede$

**Comment by wongsyrone** [comment]
你是用sdk还是自己编译的工具链？

**Comment by Sense1988** [comment]
自己clone下来的lede源码

**Comment by kalonelee** [comment]
遇到相同的错误,用的是lede-sdk-17.01.4-x86-generic_gcc-5.4.0_musl-1.1.16.Linux-x86_64

**Comment by chengr28** [comment]
问题是出在这里：
```
/home/jungle/hdd/lede/staging_dir/toolchain-x86_64_gcc-5.5.0_musl/lib/gcc/x86_64-openwrt-linux-musl/5.5.0/include/mm_malloc.h:34:64: error: declaration of 'int posix_memalign(void**, size_t, size_t) throw ()' has a different exception specifier
extern "C" int posix_memalign (void , size_t, size_t) throw ();
^
```
https://gcc.gnu.org/ml/gcc-patches/2015-05/msg01425.html
看起来是 musl 的问题。

**Comment by wongsyrone** [comment]
应该已经在openwrt主分支修复了，所以先用snapshot版本吧
