### ISSUE TITLE
不要把 Error.log 保存到 /etc/pcap-dnsproxy 下

### ISSUE THREAD

**Issue by LGA1150** [wongsyrone/openwrt-Pcap_DNSProxy#38]
占用 flash 空间且影响寿命
建议保存到 /var/log

**Comment by wongsyrone** [comment]
这个貌似是程序写死的，你可以问一下 @chengr28

**Comment by LGA1150** [comment]
写个 patch 替换一下路径？

**Comment by wongsyrone** [comment]
我倾向于做成配置项或者命令行

**Comment by LGA1150** [comment]
其实直接 log 到 OpenWrt 系统日志最好

**Comment by wongsyrone** [comment]
这个需要代码把log输出到标准输出或者错误输出上，经过procd的重定向就到系统日志了

**Comment by wongsyrone** [comment]
缺点是会被后来的系统日志覆盖掉

**Comment by chengr28** [comment]
现在的逻辑应该是有一部分（在命令行或非守护模式）情况下，会输出到 stderr 去，但是全部日志无论什么情况都会输出到同目录下的 Error.log 当然如果不想看到日志，最好的方法是直接禁用，不过这个 issue 意思是想有个可以指定保存日志的位置，还是说用 stderr 就行？

**Comment by wongsyrone** [comment]
应该是指定保存日志的地方，对OpenWrt来说放到/tmp就行，一般这个目录是映射到内存里面的，写入对flash没有什么损害，其实如果有对应的宏定义，我可以加个patch

**Comment by chengr28** [comment]
log 的完整位置是一个叫 `Path_ErrorLog` 的变量控制的，如果硬编码的话可以加一句直接抹掉原来的值。不过说回来是有个问题，如果可以通过配置文件指定储存的位置，那读取到配置文件位置之前的 log 要输出到什么地方？

**Comment by wongsyrone** [comment]
可以stderr，在OpenWrt里面会把stdout和stderr都导向到系统日志里面

**Comment by wongsyrone** [comment]
Done in https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/commit/d6c80df79ebc1764bc52944c78d1eeb39a28c71c
