### ISSUE TITLE
缺少libssl.so.1.0.0

### ISSUE THREAD

**Issue by iamsurfing** [wongsyrone/openwrt-Pcap_DNSProxy#40]
这个问题我表示看不懂

make[2]: Entering directory '/home/user/git/openwrt/package/pcap-dnsproxy'
(cd /home/user/git/openwrt/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/pcap-dnsproxy-0.4.9.7; CFLAGS="-pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -ansi -pedantic -Wall -Wextra -fpic -O3 " CXXFLAGS="-pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -msoft-float -ansi -pedantic -Wall -Wextra -fpic -O3 " LDFLAGS="-L/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -L/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lib -L/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=mipsel -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -L/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lib -L/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -L/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lib -L/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib -L/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/lib -L/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/lib" -DCMAKE_AR="/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ar" -DCMAKE_RANLIB="/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-uclibc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2;/home/user/git/openwrt/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2 -DCMAKE_PREFIX_PATH=/home/user/git/openwrt/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2 -DPLATFORM_OPENWRT=ON -DENABLE_LIBSODIUM=ON -DENABLE_PCAP=ON -DENABLE_TLS=ON . )
cmake: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

user@linux:~/git/openwrt$ find -iname libssl.so.1.0.0
./build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/openssl-1.0.2f/ipkg-ramips_24kec/libopenssl/usr/lib/libssl.so.1.0.0
./build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/openssl-1.0.2f/libssl.so.1.0.0
./build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/openssl-1.0.2f/ipkg-install/usr/lib/libssl.so.1.0.0
./staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/root-ramips/usr/lib/libssl.so.1.0.0
./staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/usr/lib/libssl.so.1.0.0
user@linux:~/git/openwrt$ find -iname *.ipk
./bin/ramips/packages/base/libpcap_1.5.3-1_ramips_24kec.ipk
./bin/ramips/packages/base/libgcc_4.8-linaro-1_ramips_24kec.ipk
./bin/ramips/packages/base/libevent2_2.0.21-1_ramips_24kec.ipk
./bin/ramips/packages/base/libstdcpp_4.8-linaro-1_ramips_24kec.ipk
./bin/ramips/packages/base/libopenssl_1.0.2f-1_ramips_24kec.ipk
./bin/ramips/packages/base/libc_0.9.33.2-1_ramips_24kec.ipk
./bin/ramips/packages/base/zlib_1.2.8-1_ramips_24kec.ipk
./bin/ramips/packages/base/libpthread_0.9.33.2-1_ramips_24kec.ipk
./bin/ramips/packages/libsodium/libsodium_1.0.10-1_ramips_24kec.ipk

**Comment by wongsyrone** [comment]
你使用的是gcc-4.8-linaro，太老了，已经不受支持。

**Comment by wongsyrone** [comment]
补充一下最低要求，在文档目录里面有。

```
  * 依赖工具/库列表：
    * 源代码编译器，必须完整支持 C++ 14 标准，可任选其一：
      * GCC/g++ 最低版本要求为 5.0
      * Clang/LLVM 最低版本要求为 3.4
```
