### ISSUE TITLE
请问为什么对于国内域名解析，不推荐使用本程序？

### ISSUE THREAD

**Issue by waeart** [wongsyrone/openwrt-Pcap_DNSProxy#47]
Windows 版是作为国内和国外域名解析使用，为什么 Openwrt 版不推荐对国内域名解析？
从 Windows 版复制配置文件到 Openwrt 版，如果不对国内域名解析，需要修改配置文件吗？
谢谢。

**Comment by wongsyrone** [comment]
这个属于个人配置偏好，需要配合其他项目达到良好的分流解析效果。
若不对国内域名解析，则不需额外配置。

**Comment by sunon78** [comment]
也可以对国内域名解析，我都是把Local Main DNS Address设成当地isp分配的dns，local host=1 local routing=0 Local Force Request=1 不用配合其他的项目，也达到了分流的效果
