### ISSUE TITLE
内存占用19%

### ISSUE THREAD

**Issue by waeart** [wongsyrone/openwrt-Pcap_DNSProxy#48]
请问能改善一下内存占用率吗？

root@OpenWrt:/proc/5216# cat status
Name:	Pcap_DNSProxy
Umask:	0022
State:	S (sleeping)
Tgid:	5216
Ngid:	0
Pid:	5216
PPid:	1
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	256
Groups:	 
VmPeak:	   26688 kB
VmSize:	   23700 kB
VmLck:	      36 kB
VmPin:	       0 kB
VmHWM:	   22536 kB
VmRSS:	   20468 kB
RssAnon:	    2120 kB
RssFile:	   18344 kB
RssShmem:	       4 kB
VmData:	    3516 kB
VmStk:	     132 kB
VmExe:	     616 kB
VmLib:	    4952 kB
VmPTE:	      32 kB
VmPMD:	       0 kB
VmSwap:	       0 kB
Threads:	21
SigQ:	0/978
SigPnd:	00000000000000000000000000000000
ShdPnd:	00000000000000000000000000000000
SigBlk:	00000000000000000000000000000000
SigIgn:	00000000000000000000000000001000
SigCgt:	00000000000000000000000000004007
CapInh:	0000000000000000
CapPrm:	0000003fffffffff
CapEff:	0000003fffffffff
CapBnd:	0000003fffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Speculation_Store_Bypass:	unknown
Cpus_allowed:	1
Cpus_allowed_list:	0
voluntary_ctxt_switches:	19
nonvoluntary_ctxt_switches:	68

**Comment by wongsyrone** [comment]
@chengr28

**Comment by waeart** [comment]
PID	用户名	命令	                                  CPU 使用率（%）	内存使用率（%）
2066	root	/usr/sbin/Pcap_DNSProxy --config-path /etc/pcap-dnsproxy --disable-daemon --log-file/tmp/pcap-dnsproxy-error.log	                0%	19%
3054	dnsmasq	/usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.cfg01411c -k -x/var/run/dnsmasq/dnsmasq.cfg01411c.pid	0%	8%
1889	root	ss-local -c /var/etc/shadowsocks.cfg064a8f.json -u -l 1080 --mtu 1492 -f /var/run/ss-local-cfg064a8f.pid	                                                0%	1%

**Comment by chengr28** [comment]
内存实际上应该是虚高了的，根据运行库内存分配策略不同而不同，详情可以参见 https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/issues/5 的讨论。最近为了适应长连接的用途重整网络模块，多线程的架构已经会被换掉，资源占用应该可以下降不少的。

**Comment by waeart** [comment]
明白了，谢谢回复，静待更新。
