### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by fuqiang03** [wongsyrone/openwrt-Pcap_DNSProxy#49]
[windows.txt](https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/files/2660476/windows.txt)
openwrt-18.06 gcc7.3 编译出错
Source/Pcap_DNSProxy/Network.cpp 文件出错

**Comment by chengr28** [comment]
请移步 https://github.com/chengr28/Pcap_DNSProxy/issues/392

**Comment by fuqiang03** [comment]
xiexie
