### ISSUE TITLE
High VSZ and System load cause termination

### ISSUE THREAD

**Issue by legendtang** [wongsyrone/openwrt-Pcap_DNSProxy#5]
在 OpenWrt 15.05 CC brcm63xx 平台上出现内存占用极高的情况，并且一开启就会出现
````
PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
23176     1 root     S    50568  83%   3% /usr/sbin/Pcap_DNSProxy -c /etc/pcap-
````
导致系统负载长期在 2~3，并且运行一段时间后崩溃，功能使用并无异常

实在没有找到日志文件 Error.log，可能是程序并未报错？logread 没有看到相关输出
确认如果是上游问题将反馈给上游

另，请求添加回预编译 brcm63xx target，谢谢！使用的版本为 0.4.4.4

抱歉，没有看到，似乎关于内存占用的描述与 https://github.com/chengr28/Pcap_DNSProxy/issues/37 一致

**Comment by wongsyrone** [comment]
尝试过手动gcc 5编译吗

**Comment by wongsyrone** [comment]
下个版本加回CC的brcm63xx

**Comment by legendtang** [comment]
没有尝试手动 gcc 5……Linux 系统最近重做了，build system 得过段时间再搞了

**Comment by wongsyrone** [comment]
先关掉了，如果手动gcc 5编译之后依然存在内存泄露，可以再开

**Comment by chengr28** [comment]
关于这个 VSZ 很高的事情，详细查阅了相关的资料

VSZ 这个是虚拟内存的大小，也就是说程序要求要多少，这里就会出现多少，但是由于程序本身的内存分配是 API 包装好的，也就是说是其它的库而非程序本身负责的，在 Linux 里一般是 glibc 在 OpenWrt 里是 uClibc
而这个数据很高和 Linux 的内存管理机制有关，为了节省分配内存所带来的开销，会通过一定的算法维持一个内存池供使用……当然还有很多细节上的东西。总体思想就是除非系统/其它程序有需要否则不会释放，这点应该比较像 OS X 而和 Windows 不同，这部分空间被算到 VSZ 里了
所以最后出来的结果就是 VSZ 非常高，尤其是程序还使用了多线程的结构，开一个线程分配一点空间 VSZ 直接就是一两百 MB（桌面 Linux 环境，POSIX Pthread 线程占用的内存非常多）但实际占用的内存却非常小只有几 MB 刚才也说到 VSZ 这部分是预占用的，也就是说除了实际占用那几 MB 的空间，其它成百上千 MB 的 VIRT 是随时可以被其它程序使用或者被系统收回的，所以内存占用的问题无须担心
关于这个 VSZ 的占用，貌似是可以通过调整系统栈大小参数来进行调整的。当然系统架构和版本之类的都有关，不过既然并没有实际的影响，调不调都没有所谓……只是会看着很恐怖就是了
参见 http://udrepper.livejournal.com/20948.html

**Comment by legendtang** [comment]
@chengr28 确实如你所说，对运行速度没什么影响，但 VSZ 占用并不能解释：

1. 系统负载过高
2. 程序异常提前终止，没有任何日志和错误输出

@wongsyrone 前两天拿新的 nightly SDK with GCC 5 没有编译成功，得哪天抽时间从源编译了

**Comment by wongsyrone** [comment]
@legendtang SDK编译错误的log还有么，可以贴出来看看，我发布的预编译包都是用官方SDK编译的

**Comment by wongsyrone** [comment]
@legendtang  至于程序异常提前终止，之前的版本怎么样，SF中有全部发布过的版本，如果旧版本没问题，那就是新引入的bug

**Comment by wongsyrone** [comment]
GCC 5.2 Trunk + musl-libc + pcap-dnsproxy v0.4.5
```
Mem: 149392K used, 105508K free, 5240K shrd, 17124K buff, 61328K cached
CPU:   0% usr   0% sys   0% nic  95% idle   0% io   0% irq   2% sirq
Load average: 0.37 0.24 0.23 2/93 20852
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
20352     1 root     S    12424   5%   1% /usr/bin/transmission-daemon -g /mnt/
 1604     1 root     S    14980   6%   0% /usr/sbin/Pcap_DNSProxy -c /etc/pcap-
```
作为对比，可以看到和transmission的占用差不太多，运行状态貌似没什么异常，所以很可能是uclibc或者是GCC的锅

**Comment by legendtang** [comment]
@wongsyrone 请问 sourceforge 上的 brcm63xx 最新版 v0.4.5v是 GCC 5 编译的吗？占用率依然这么多

**Comment by wongsyrone** [comment]
不是，全是官方SDK编译的，gcc 4.8

**Comment by wongsyrone** [comment]
@legendtang 如果要换GCC版本的话还是需要从头编译的，因为libc、libgcc这两个核心软件包升级安装的话要么导致依赖他们的其他包不正常，要么pcap-dnsproxy工作不正常，还是不要冒险，手动编译比较好

**Comment by legendtang** [comment]
@wongsyrone 我今天切 Linux 看了下，用 SDK `make menuconfig` 这步出现了问题，不知道是不是发行版的问题。
````
Collecting package info: done
tmp/.config-package.in:8:warning: ignoring type redefinition of 'PACKAGE_base-files' from 'boolean' to 'tristate'
tmp/.config-package.in:55:warning: ignoring type redefinition of 'PACKAGE_busybox' from 'boolean' to 'tristate'
feeds/base/package/utils/busybox/config/Config.in:818: glob failed: No files found "package/utils/busybox/config/libbb/Config.in"
/home/legend/OpenWrt-SDK-brcm63xx-generic_gcc-5.2.0_musl-1.1.11.Linux-x86_64/include/toplevel.mk:112: recipe for target 'menuconfig' failed
make: *** [menuconfig] Error 1
````

**Comment by wongsyrone** [comment]
glob failed这个的最好去确认一下，前面的warning没问题

**Comment by legendtang** [comment]
@wongsyrone 是上游的问题，我已经写好 patch 了然而管理层还没通过我的 mailing list
····
Once reported at https://dev.openwrt.org/ticket/18552. When using SDK we shouldn't use absolute path in the Config.in.

Signed-off-by: Wensheng Tang <sp3478@gmail.com>

---
 package/utils/busybox/config/Config.in            | 43 ++++++++++++++++++++++---------------------
 package/utils/busybox/config/networking/Config.in |  2 +-
 package/utils/busybox/config/util-linux/Config.in |  2 +-
 3 files changed, 24 insertions(+), 23 deletions(-)

diff --git a/package/utils/busybox/config/Config.in b/package/utils/busybox/config/Config.in
index 6a205f6..896aed7 100644
--- a/package/utils/busybox/config/Config.in
+++ b/package/utils/busybox/config/Config.in
@@ -815,29 +815,30 @@ config BUSYBOX_CONFIG_PREFIX
 
 endmenu
 
-source package/utils/busybox/config/libbb/Config.in
+source libbb/Config.in
 
 endmenu
 
 comment "Applets"
 
-source package/utils/busybox/config/archival/Config.in
-source package/utils/busybox/config/coreutils/Config.in
-source package/utils/busybox/config/console-tools/Config.in
-source package/utils/busybox/config/debianutils/Config.in
-source package/utils/busybox/config/editors/Config.in
-source package/utils/busybox/config/findutils/Config.in
-source package/utils/busybox/config/init/Config.in
-source package/utils/busybox/config/loginutils/Config.in
-source package/utils/busybox/config/e2fsprogs/Config.in
-source package/utils/busybox/config/modutils/Config.in
-source package/utils/busybox/config/util-linux/Config.in
-source package/utils/busybox/config/miscutils/Config.in
-source package/utils/busybox/config/networking/Config.in
-source package/utils/busybox/config/printutils/Config.in
-source package/utils/busybox/config/mailutils/Config.in
-source package/utils/busybox/config/procps/Config.in
-source package/utils/busybox/config/runit/Config.in
-source package/utils/busybox/config/selinux/Config.in
-source package/utils/busybox/config/shell/Config.in
-source package/utils/busybox/config/sysklogd/Config.in
+source archival/Config.in
+source coreutils/Config.in
+source console-tools/Config.in
+source debianutils/Config.in
+source editors/Config.in
+source findutils/Config.in
+source init/Config.in
+source loginutils/Config.in
+source e2fsprogs/Config.in
+source modutils/Config.in
+source util-linux/Config.in
+source miscutils/Config.in
+source networking/Config.in
+source printutils/Config.in
+source mailutils/Config.in
+source procps/Config.in
+source runit/Config.in
+source selinux/Config.in
+source shell/Config.in
+source sysklogd/Config.in
+
diff --git a/package/utils/busybox/config/networking/Config.in b/package/utils/busybox/config/networking/Config.in
index 40b3c68..7e5a414 100644
--- a/package/utils/busybox/config/networking/Config.in
+++ b/package/utils/busybox/config/networking/Config.in
@@ -1111,7 +1111,7 @@ config BUSYBOX_CONFIG_FEATURE_TUNCTL_UG
          Allow to specify owner and group of newly created interface.
          340 bytes of pure bloat. Say no here.
 
-source package/utils/busybox/config/networking/udhcp/Config.in
+source udhcp/Config.in
 
 config BUSYBOX_CONFIG_IFUPDOWN_UDHCPC_CMD_OPTIONS
        string "ifup udhcpc command line options"
diff --git a/package/utils/busybox/config/util-linux/Config.in b/package/utils/busybox/config/util-linux/Config.in
index 8c87f53..017b119 100644
--- a/package/utils/busybox/config/util-linux/Config.in
+++ b/package/utils/busybox/config/util-linux/Config.in
@@ -800,6 +800,6 @@ config BUSYBOX_CONFIG_FEATURE_MTAB_SUPPORT
          About the only reason to use this is if you've removed /proc from
          your kernel.
 
-source package/utils/busybox/config/util-linux/volume_id/Config.in
+source volume_id/Config.in
 
 endmenu
····
编译成功了，但是依赖确实升级不得，所有二进制必须从头用 GCC5 编译，而且我现在主路由器是 CC 不太想用 snapshot…

只能过段时间试试另外一台 ar71xx 了

**Comment by wongsyrone** [comment]
@legendtang 每次更新都要bump PKG_RELEASE 的

**Comment by wongsyrone** [comment]
@legendtang 我一直在Config-defaults.in里面改设置，没注意到路径的问题，感谢提交给上游

**Comment by wongsyrone** [comment]
@legendtang 可以尝试一下0.4.5.1-1是否还有程序异常提前终止的问题

**Comment by legendtang** [comment]
已经安装并试用，由于随机性较强需要观察一段时间才会出现，届时会报告

**Comment by wongsyrone** [comment]
@legendtang 如果复现的话，尝试添加这个补丁 https://gist.github.com/wongsyrone/680308ca185b71705bda 再次编译测试

**Comment by legendtang** [comment]
昨天出现了崩溃，遗憾的是仍然没有 Error.log 出现，有时间 patch 一下试试

**Comment by wongsyrone** [comment]
既然不是运行后立即崩溃，而且没有错误日志，我更倾向于哪个部分的指针处理问题或者是OP系统资源不足，之前我的经验是linux 4.1.13的内核貌似处理网络这部分有点问题，换成4.1.15的话延迟会有一定的好转，如果带USB口的话可以考虑挂一个swap进行测试，trunk的下一步是所有target统一换成linux 4.4，估计距离新release不远了

**Comment by legendtang** [comment]
同意，从 system load 的情况来看，pcap-dnsproxy 本身采用的分配虚拟内存 + 多线程暂时不适合在 MIPS 嵌入式设备上运行，感觉这样很容易被调度算法误判挤掉。有 GCC 5 和 Linux Kernel 4.4 LTS 可能会好一些吧

**Comment by chengr28** [comment]
VSZ 过高其实本质还是多线程造成的……实测开一个线程几十几十 MB 地占
并不是程序想多占……实际上程序真正需要的很少

**Comment by wongsyrone** [comment]
也有可能并没有及时释放，对于嵌入式设备来说，确实承受不了几个几十MB，一般是64MB，稍微好点的128MB或者256MB

**Comment by wongsyrone** [comment]
OP trunk在 https://github.com/openwrt-mirror/openwrt/commit/f53973b27d4d3f467d9e1bf955b2c934284e2657 移除了GCC 4.8，下一个release应该不远了，可以等下一个正式版发布之后再次测试，毕竟项目本身从开始就要求GCC版本高于4.9，目前显现的问题可以考虑暂时搁置，于是关于这个问题大家怎么看？

另外，在gitter里面也有人反馈会程序会莫名终止，重开了

**Comment by wongsyrone** [comment]
> 0.4.5.3 修复了一个可能导致程序毫无征兆崩溃的问题，可以更新试试w

目前预编译包正在上传，不过坑爹的SF太慢了，可以自己用SDK编译

**Comment by wongsyrone** [comment]
由于SF太慢了，已经将所有预编译包转移到 prebuilt-ipks 分支，以后的版本也会传到这里，SF不再更新。

**Comment by legendtang** [comment]
谢谢，最近暂时没有机会测试，可能要等 16.xx 以后了
> 由于SF太慢了，已经将所有预编译包转移到 prebuilt-ipks 分支，以后的版本也会传到这里，SF不再更新。
为什么不直接丢到 release 里呢？

**Comment by wongsyrone** [comment]
因为BB和CC所有的ipk包上百个，为了满足绝大部分需求，保留了一部分历史版本方便用户回滚或者做测试什么的，放在release里面会显得比较乱，放在某个分支的目录中用户只需要记住特定的地址，定期去查看即可。

**Comment by legendtang** [comment]
@wongsyrone 我今天无法下载 https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/blob/prebuilt-ipks/chaos_calmer/15.05/ar71xx/generic/libpcap_1.7.4-1_ar71xx.ipk 不知道是不是 Git LFS 出问题了

**Comment by wongsyrone** [comment]
@legendtang 不用 Git LFS 了，重新推送了一遍，现在应该可以了

**Comment by wongsyrone** [comment]
Please feel free to reopen if the issue persists.

**Comment by roc1010kmt** [comment]
怎麼編譯沒看太明白，請問能否編譯一個ar71xx路由器用的？
