### ISSUE TITLE
网件Wndr4300安装失败，提示Cannot satisfy the following dependencies for pcap-dnsproxy

### ISSUE THREAD

**Issue by c1024** [wongsyrone/openwrt-Pcap_DNSProxy#6]
今天下载了最新的ipk安装，结果安装失败，提示
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for pcap-dnsproxy:
 * 	libstdcpp *
 * opkg_install_cmd: Cannot install package pcap-dnsproxy.
路由器是网件Wndr4300, OpenWrt版本是14.07.

**Comment by wongsyrone** [comment]
opkg install libstdcpp

**Comment by c1024** [comment]
找不到这个包，执行结果如下：
root@OpenWrt:~#opkg install libstdcpp
Unknown package 'libstdcpp'.
Collected errors:
 * opkg_install_cmd: Cannot install package libstdcpp.

**Comment by wongsyrone** [comment]
首先运行opkg update，然后再运行安装的命令，你是第一次用openwrt吧。

**Comment by wongsyrone** [comment]
OPKG的使用参考：https://wiki.openwrt.org/doc/techref/opkg
libstdcpp在 https://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/nand/packages/base/libstdcpp_4.8-linaro-1_ar71xx.ipk

**Comment by c1024** [comment]
谢谢，已经安装上了
