### ISSUE TITLE
安装完后，国外域名无法解析

### ISSUE THREAD

**Issue by c1024** [wongsyrone/openwrt-Pcap_DNSProxy#7]
按照说明安装成功后，发现国外域名无法解析，国内域名是用dnsmasq-china-list ，可以正常解析。用top和ps命令查看进程发现pcap-dnsproxy不存在。路由器是网件Wndr4300,系统14.07.

**Comment by dgeibi** [comment]
修改 /etc/rc.local

在 exit 0 前加

```
sleep 10
/etc/init.d/pcap-dnsproxy start
```

可以解决开机不启动的问题

**Comment by wongsyrone** [comment]
进程名不是pcap-dnsproxy而是Pcap_DNSProxy。发的0.4.5-3新加了个status的命令，如果运行的话可以看到PID

**Comment by wongsyrone** [comment]
@c1024 如果还不行，安装dig并按照chengr28的方法进行验证：https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/issues/4#issuecomment-164425954

**Comment by c1024** [comment]
谢谢，我明天试一下

**Comment by c1024** [comment]
原来是用luci设置开机启动不行，后来用/etc/init.d/pcap-dnsproxy enable就可以看到Pcap_DNSProxy进程了。但是dns查询还是不行。开启DNSCurve的情况下测试，dig @8.8.4.4 twitter.com可以，dig @10.0.99.1 -p 1053 dl.google.com不行。10.0.99.1是路由器ip,1053是Pcap_DNSProxy监听端口

**Comment by wongsyrone** [comment]
开DNSCurve需要调整op的时区和日期时间设置，另外有Error.log么

**Comment by c1024** [comment]
调整时区和日期后还是不行。Erro.log如下
2016-01-13 10:33:09 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
2016-01-13 10:33:09 -> DNSCurve Error: IPv4 Main Server UDP get signature data error.

**Comment by wongsyrone** [comment]
换一个DNSCurve的DNS地址，默认的可能被屏蔽了，获取不到签名就起不到应有的作用，我记得之前好像看过那个csv里面的地址绝大部分gfw都知道了

**Comment by c1024** [comment]
dig的输出如下：
dig @127.0.0.1 -p 1053 dl.google.com

; <<>> DiG 9.9.4 <<>> @127.0.0.1 -p 1053 dl.google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached。

这是不是连不上Pcap_DNSProxy?

**Comment by wongsyrone** [comment]
先关掉dnscurve测一下

**Comment by c1024** [comment]
关了也有测过，也是这样

**Comment by wongsyrone** [comment]
GCC 5.2 + Trunk开发版 + mvebu ，0.4.5-3, 只开了EDNS Label
```
root@OpenWrt:~# dig @127.0.0.1 -p 1053 dl.google.com

; <<>> DiG 9.9.7-P3 <<>> @127.0.0.1 -p 1053 dl.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55540
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dL.GoOgLe.cOm.                 IN      A

;; ANSWER SECTION:
dL.GoOgLe.cOm.          21599   IN      CNAME   dl.l.GoOgLe.cOm.
dl.l.GoOgLe.cOm.        299     IN      A       216.58.199.14

;; Query time: 252 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Wed Jan 13 12:27:08 CST 2016
;; MSG SIZE  rcvd: 77

root@OpenWrt:~# dig @192.168.1.1 -p 1053 dl.google.com

; <<>> DiG 9.9.7-P3 <<>> @192.168.1.1 -p 1053 dl.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19309
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dL.GoOgLe.cOm.                 IN      A

;; ANSWER SECTION:
dL.GoOgLe.cOm.          21599   IN      CNAME   dl.l.GoOgLe.cOm.
dl.l.GoOgLe.cOm.        299     IN      A       216.58.199.14

;; Query time: 1 msec
;; SERVER: 192.168.1.1#1053(192.168.1.1)
;; WHEN: Wed Jan 13 12:27:20 CST 2016
;; MSG SIZE  rcvd: 77
```
连续两次查询，第二次明显是缓存内的结果。
我现在怀疑是GCC 4.8的问题

**Comment by wongsyrone** [comment]
@c1024 
用BB的ar71xx nand SDK编译了一份dig，安装上去用这个测一下： https://copy.com/ZcYrO83YoSpCNkdc

**Comment by c1024** [comment]
@wongsyrone 安装你编译的dig,还是不行。
开启DNSCurve，结果如下
2016-01-13 14:19:08 -> DNSCurve Error: IPv4 Alternate Server UDP get signature data error.
2016-01-13 14:19:08 -> DNSCurve Error: IPv4 Main Server UDP get signature data error.

dig也是不行，结果如下：
dig @127.0.0.1 -p 1053 dl.google.com

; <<>> DiG 9.9.7-P3 <<>> @127.0.0.1 -p 1053 dl.google.com
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

**Comment by wongsyrone** [comment]
另外一个Qihoo C301用GCC 5.2 + Trunk + pcap-dnsproxy 0.4.5-3
```
root@OpenWrt:~# dig @127.0.0.1 -p 1053 dl.google.com

; <<>> DiG 9.9.7-P3 <<>> @127.0.0.1 -p 1053 dl.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10926
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dL.GoOgLe.cOm.                 IN      A

;; ANSWER SECTION:
dL.GoOgLe.cOm.          604800  IN      CNAME   dl.l.GoOgLe.cOm.
dl.l.GoOgLe.cOm.        300     IN      A       216.58.221.78

;; Query time: 129 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Wed Jan 13 21:07:44 CST 2016
;; MSG SIZE  rcvd: 77
```
只修改 DNSCurve = 1

**Comment by wongsyrone** [comment]
@c1024 可以参考 https://github.com/chengr28/Pcap_DNSProxy/issues/95 里面的对话用tcpdump抓一下包看看问题出在哪里。

现在不确定的是：
- 网络环境比较差
- 设置不正确
- 编译工具链尤其是GCC的问题

为了分辨一下
1. 如果你有奇虎C301这个路由的话，我可以把编译好的带pcap-dnsproxy的固件发给你。
2. 抓包分析看看在哪里卡住的
3. 手动用GCC 5.2编译固件（目前只有Trunk才有这个版本的GCC），在同样的网络环境下测试，如果正常说明是Toolchain的问题，如果依然不正常，再继续找其他的可能

**Comment by c1024** [comment]
@wongsyrone 我手上只有Wndr4300这个路由。
现在发现是跟chengr28/Pcap_DNSProxy#95 这个里面同样问题，Tcp行，UDP不行。
root@OpenWrt:~# dig +vc @127.0.0.1 -p 1053 google.com

; <<>> DiG 9.9.7-P3 <<>> +vc @127.0.0.1 -p 1053 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52901
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;GoOgLe.cOm.			IN	A

;; ANSWER SECTION:
GoOgLe.cOm.		299	IN	A	216.58.220.238

;; Query time: 185 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Thu Jan 14 09:40:27 CST 2016
;; MSG SIZE  rcvd: 55

**Comment by wongsyrone** [comment]
同样问题的话按照那个Issue的信息用tcpdump抓一下包，然后发上来，顺便 @chengr28

**Comment by wongsyrone** [comment]
@c1024 
手动编译了一个GCC 5.2的wndr4300固件，可以用这个测试一下，集成dig、tcpdump、pcap-dnsproxy、luci界面，应该没什么问题，不过还是自备救砖方法。https://drive.google.com/folderview?id=0B1sYxTw9JX7-WWQzZzdFVGxJVDg&usp=sharing

**Comment by c1024** [comment]
@wongsyrone ,谢谢回复。我发现问题了，pcap-dnsproxy应该是跟我路由器上跑的ShadowVPN发生冲突，关掉ShadowVPN就正常了。

**Comment by wongsyrone** [comment]
既然这样就关掉这个Issue了

**Comment by chengr28** [comment]
程序默认配置是通过抓包模块抓取远程 DNS 服务器回复的结果的，发送请求的话和其它程序一样使用系统的 API 也就是要求请求是直接连接。开了 VPN 会导致程序发出的请求通过代理服务器进行，由于 VPN 普遍采用了加密连接而导致抓包模块无法抓取回复，自然也就没法返回结果了……
解决这个问题需要开启 Direct Request 直接连接的选项，TCP 方式可以获取结果是因为 TCP 本身完全依靠系统 API 进行不需要抓包模块的帮助，也就是全程被代理了，关于这点说明文档是有介绍的：**如需让程序的流量通过系统路由级别的代理（例如 VPN 等）进行域名解析，请选择其中一种方案，配置完成后重启服务..**

**Comment by roc1010kmt** [comment]
怎麼編譯沒看太明白，請問能否編譯一個ar71xx路由器用的？
