### ISSUE TITLE
安装错误 求解

### ISSUE THREAD

**Issue by gaoyan1234** [wongsyrone/openwrt-Pcap_DNSProxy#8]
root@OpenWrt:~# opkg install ./pcap-dnsproxy_0.4.5.3-1_ramips_24kec.ipk  --force
-depends
Collected errors:
 * deb_extract: ./pcap-dnsproxy_0.4.5.3-1_ramips_24kec.ipk: invalid magic
 * pkg_init_from_file: Failed to extract control file from ./pcap-dnsproxy_0.4.5.3-1_ramips_24kec.ipk.
root@OpenWrt:~#

**Comment by wongsyrone** [comment]
Do NOT use ` --force-depends` when installing packages via opkg.

**Comment by wongsyrone** [comment]
Try downloading from [here](https://github.com/wongsyrone/openwrt-Pcap_DNSProxy/tree/prebuilt-ipks).

**Comment by gaoyan1234** [comment]
The same error .I   was downloaded from  the  official website of you  and my router is  斐讯PSG1208（mt7620） and  the openwrt is from https://downloads.openwrt.org/chaos_calmer/15.05/

**Comment by wongsyrone** [comment]
Paste the output of `opkg list-installed` plz.

**Comment by gaoyan1234** [comment]
root@OpenWrt:~# opkg list-installed
aiccu - 20070115-12
base-files - 157.2-r48749
busybox - 1.23.2-1
ddns-scripts - 2.4.3-2
ddns-scripts_no-ip_com - 2.4.3-2
dnsmasq-full - 2.73-1
dropbear - 2015.67-1
ds-lite - 7-1
firewall - 2015-07-27
fstools - 2016-01-10-96415afecef35766332067f4205ef3b2c7561d21
hostapd-common - 2015-03-25-1
ip - 4.0.0-1
ip6tables - 1.4.21-1
ipset - 6.24-1
iptables - 1.4.21-1
iptables-mod-conntrack-extra - 1.4.21-1
iptables-mod-filter - 1.4.21-1
iptables-mod-hashlimit - 1.4.21-1
iptables-mod-imq - 1.4.21-1
iptables-mod-ipopt - 1.4.21-1
iptables-mod-nat-extra - 1.4.21-1
iptables-mod-tproxy - 1.4.21-1
iputils-traceroute6 - 20101006-1
iw - 3.17-1
iwinfo - 2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371
jshn - 2015-11-08-10429bccd0dc5d204635e110a7a8fae7b80d16cb
jsonfilter - 2014-06-19-cdc760c58077f44fc40adbbe41e1556a67c1b9a9
kernel - 3.18.23-1-7c821627275b0048120f5d0e8157e5ef
kmod-atm - 3.18.23-1
kmod-cfg80211 - 3.18.23+2015-03-09-3
kmod-crypto-aead - 3.18.23-1
kmod-crypto-aes - 3.18.23-1
kmod-crypto-arc4 - 3.18.23-1
kmod-crypto-core - 3.18.23-1
kmod-crypto-ecb - 3.18.23-1
kmod-crypto-hash - 3.18.23-1
kmod-crypto-manager - 3.18.23-1
kmod-crypto-pcompress - 3.18.23-1
kmod-crypto-sha1 - 3.18.23-1
kmod-eeprom-93cx6 - 3.18.23-1
kmod-gpio-button-hotplug - 3.18.23-1
kmod-gre - 3.18.23-1
kmod-i2c-core - 3.18.23-1
kmod-ip6-tunnel - 3.18.23-1
kmod-ip6tables - 3.18.23-1
kmod-ipt-conntrack - 3.18.23-1
kmod-ipt-conntrack-extra - 3.18.23-1
kmod-ipt-core - 3.18.23-1
kmod-ipt-filter - 3.18.23-1
kmod-ipt-hashlimit - 3.18.23-1
kmod-ipt-imq - 3.18.23-1
kmod-ipt-ipopt - 3.18.23-1
kmod-ipt-ipset - 3.18.23-1
kmod-ipt-nat - 3.18.23-1
kmod-ipt-nat-extra - 3.18.23-1
kmod-ipt-nat6 - 3.18.23-1
kmod-ipt-tproxy - 3.18.23-1
kmod-iptunnel - 3.18.23-1
kmod-iptunnel4 - 3.18.23-1
kmod-iptunnel6 - 3.18.23-1
kmod-ipv6 - 3.18.23-1
kmod-l2tp - 3.18.23-1
kmod-leds-gpio - 3.18.23-1
kmod-leds-pca963x - 3.18.23-1
kmod-ledtrig-default-on - 3.18.23-1
kmod-ledtrig-gpio - 3.18.23-1
kmod-ledtrig-netdev - 3.18.23-1
kmod-ledtrig-timer - 3.18.23-1
kmod-lib-crc-ccitt - 3.18.23-1
kmod-lib-crc-itu-t - 3.18.23-1
kmod-lib-textsearch - 3.18.23-1
kmod-mac80211 - 3.18.23+2015-03-09-3
kmod-macvlan - 3.18.23-1
kmod-mppe - 3.18.23-1
kmod-mt76 - 3.18.23+2015-10-12-1
kmod-nf-conntrack - 3.18.23-1
kmod-nf-conntrack6 - 3.18.23-1
kmod-nf-ipt - 3.18.23-1
kmod-nf-ipt6 - 3.18.23-1
kmod-nf-nat - 3.18.23-1
kmod-nf-nat6 - 3.18.23-1
kmod-nf-nathelper - 3.18.23-1
kmod-nf-nathelper-extra - 3.18.23-1
kmod-nfnetlink - 3.18.23-1
kmod-nls-base - 3.18.23-1
kmod-nls-utf8 - 3.18.23-1
kmod-ppp - 3.18.23-1
kmod-pppoa - 3.18.23-1
kmod-pppoe - 3.18.23-1
kmod-pppol2tp - 3.18.23-1
kmod-pppox - 3.18.23-1
kmod-pptp - 3.18.23-1
kmod-rt2800-lib - 3.18.23+2015-03-09-3
kmod-rt2800-mmio - 3.18.23+2015-03-09-3
kmod-rt2800-pci - 3.18.23+2015-03-09-3
kmod-rt2800-soc - 3.18.23+2015-03-09-3
kmod-rt2x00-lib - 3.18.23+2015-03-09-3
kmod-rt2x00-mmio - 3.18.23+2015-03-09-3
kmod-rt2x00-pci - 3.18.23+2015-03-09-3
kmod-sched - 3.18.23-1
kmod-sched-core - 3.18.23-1
kmod-sit - 3.18.23-1
kmod-slhc - 3.18.23-1
kmod-tun - 3.18.23-1
kmod-udptunnel4 - 3.18.23-1
kmod-udptunnel6 - 3.18.23-1
libblobmsg-json - 2015-11-08-10429bccd0dc5d204635e110a7a8fae7b80d16cb
libc - 0.9.33.2-1
libgcc - 4.8-linaro-1
libgmp - 6.0.0-1
libip4tc - 1.4.21-1
libip6tc - 1.4.21-1
libiwinfo - 2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371
libiwinfo-lua - 2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371
libjson-c - 0.12-1
libjson-script - 2015-11-08-10429bccd0dc5d204635e110a7a8fae7b80d16cb
liblua - 5.1.5-1
libmnl - 1.0.3-2
libncurses - 5.9-2
libnettle - 3.1.1-1
libnl-tiny - 0.1-4
libopenssl - 1.0.2f-1
libpcre - 8.38-1
libpthread - 0.9.33.2-1
librt - 0.9.33.2-1
libstdcpp - 4.8-linaro-1
libubox - 2015-11-08-10429bccd0dc5d204635e110a7a8fae7b80d16cb
libubus - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
libubus-lua - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
libuci - 2015-08-27.1-1
libuci-lua - 2015-08-27.1-1
libxtables - 1.4.21-1
linux-atm - 2.5.2-5
lua - 5.1.5-1
luci - git-16.043.44305-e2f9172-1
luci-app-ddns - 2.2.4-1
luci-app-filetransfer - git-16.043.44305-e2f9172-1
luci-app-firewall - git-16.043.44305-e2f9172-1
luci-app-mwan3 - 1.4-4
luci-app-ntpc - git-16.043.44305-e2f9172-1
luci-app-syncdial - git-16.043.44305-e2f9172-1
luci-app-uhttpd - git-16.043.44305-e2f9172-1
luci-app-upnp - git-16.043.44305-e2f9172-1
luci-base - git-16.043.44305-e2f9172-1
luci-i18n-base-en - git-16.043.44305-e2f9172-1
luci-i18n-base-zh-cn - git-16.043.44305-e2f9172-1
luci-i18n-ddns-en - 2.2.4-1
luci-i18n-ddns-zh-cn - 2.2.4-1
luci-i18n-filetransfer-zh-cn - git-16.043.44305-e2f9172-1
luci-i18n-firewall-en - git-16.043.44305-e2f9172-1
luci-i18n-firewall-zh-cn - git-16.043.44305-e2f9172-1
luci-i18n-ntpc-en - git-16.043.44305-e2f9172-1
luci-i18n-ntpc-zh-cn - git-16.043.44305-e2f9172-1
luci-i18n-uhttpd-zh-cn - git-16.043.44305-e2f9172-1
luci-i18n-upnp-en - git-16.043.44305-e2f9172-1
luci-i18n-upnp-zh-cn - git-16.043.44305-e2f9172-1
luci-lib-ip - git-16.043.44305-e2f9172-1
luci-lib-nixio - git-16.043.44305-e2f9172-1
luci-mod-admin-full - git-16.043.44305-e2f9172-1
luci-proto-ipv6 - git-16.043.44305-e2f9172-1
luci-proto-ppp - git-16.043.44305-e2f9172-1
luci-theme-bootstrap - git-16.043.44305-e2f9172-1
luci-theme-material - git-16.043.44305-e2f9172-1
luci-theme-openwrt - git-16.043.44305-e2f9172-1
miniupnpd - 1.9.20150609-1
mtd - 21
mwan3 - 2.0-2
netifd - 2015-12-16-245527193e90906451be35c2b8e972b8712ea6ab
ntpclient - 2010_365-1
odhcp6c - 2015-07-13-024525798c5f6aba3af9b2ef7b3af2f3c14f1db8
odhcpd - 2015-11-19-01d3f9d64486ac1daa144848944e877e7f0cb762
opkg - 9c97d5ecd795709c8584e972bfdf3aee3a5b846d-9
ppp - 2.4.7-8
ppp-mod-pppoa - 2.4.7-8
ppp-mod-pppoe - 2.4.7-8
ppp-mod-pppol2tp - 2.4.7-8
ppp-mod-pptp - 2.4.7-8
procd - 2015-10-29.1-d5fddd91b966424bb63e943e789704d52382cc18
relayd - 2015-03-13-2970ff60bac6b70ecb682779d5c776dc559dc0b9
resolveip - 2
rpcd - 2015-01-10-f00890cd6eb47ad9bb5da0fb6c50aedc8406e7c5
shellsync - 0.2-1
swconfig - 10
tc - 4.0.0-1
terminfo - 5.9-2
ubox - 2015-11-22-c086167a0154745c677f8730a336ea9cf7d71031
ubus - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
ubusd - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
uci - 2015-08-27.1-1
uhttpd - 2015-11-08-fe01ef3f52adae9da38ef47926cd50974af5d6b7
uhttpd-mod-ubus - 2015-11-08-fe01ef3f52adae9da38ef47926cd50974af5d6b7
usign - 2015-05-08-cf8dcdb8a4e874c77f3e9a8e9b643e8c17b19131
vim - 7.4-2
wget - 1.17.1-1
wpad - 2015-03-25-1
xl2tpd - devel-20150930-1
zlib - 1.2.8-1

**Comment by wongsyrone** [comment]
如果是预编译包的话，并没有libpcap和libsodium这两个依赖。

**Comment by gaoyan1234** [comment]
什么意思啊 pcap-dnsproxy_0.4.5.3-1_ramips_24kec.ipk始终安装不上 安装 libpcap和libsodium 也是同样的错误

**Comment by wongsyrone** [comment]
如果无论什么软件包都无法安装，则是固件的问题

**Comment by gaoyan1234** [comment]
今天换了一个路由器wndr 3400 安装依然是这个错误 出了啥鬼

**Comment by wongsyrone** [comment]
```
opkg update
opkg install libstdcpp libsodium libpcap
# 复制pcap-dnsproxy的 ipk 到 /tmp
cd /tmp
opkg install pcap-dnsproxy*.ipk
```

**Comment by gaoyan1234** [comment]
root@Jingtian-router:~# opkg install libstdcpp libsodium libpcap
Package libstdcpp (4.8-linaro-1) installed in root is up to date.
Installing libsodium (1.0.2-1) to root...
Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/packages/packages/libsodium_1.0.2-1_ramips_24kec.ipk.
Installing libpcap (1.5.3-1) to root...
Downloading http://downloads.openwrt.org/chaos_calmer/15.05.1/ramips/mt7620/packages/base/libpcap_1.5.3-1_ramips_24kec.ipk.
Configuring libsodium.
Configuring libpcap.
root@Jingtian-router:~# cd /tmp/upload/
root@Jingtian-router:/tmp/upload# opkg install pcap-dnsproxy_0.4.5.6-1_ramips_24kec.ipk
Collected errors:
 * deb_extract: pcap-dnsproxy_0.4.5.6-1_ramips_24kec.ipk: invalid magic
 * pkg_init_from_file: Failed to extract control file from pcap-dnsproxy_0.4.5.6-1_ramips_24kec.ipk.
root@Jingtian-router:/tmp/upload#

依然错误 要崩溃了 之前以为是因为我的cc为15.05.1 所以会错误  可是用了新的15.05.1 依然错误  下面准备自己学着编译吧

**Comment by wongsyrone** [comment]
看样子不能正常解开ipk，我从github自己下载了一遍，可以解开。
md5: 1c83ad970881c337acc7289418f1dcd4  pcap-dnsproxy_0.4.5.6-1_ramips_24kec.ipk
如果校验没问题依然不行的话可能是opkg的问题，只能自己编译了，编译过程在主页上写的比较详细

**Comment by gaoyan1234** [comment]
感觉不是我的opkg问题 把你的ipk重命名成zip 用压缩文件也无法解压  而别的ipk 是可以解压的

**Comment by wongsyrone** [comment]
首先ipk的压缩是gzip而不是zip，其次我自己从github上下载的没有问题，上面的md5是根据你opkg的下载路径找到的包，你可能下载了不适用你CPU架构的包
